version: "2.2"

services:
  proxy:
    image: dobbs/proxy:0.5.0
    build: ./proxy
    init: true
    volumes:
      - proxy:/etc/proxy
    ports:
      - "80:80"
      - "443:443"
  web:
    build: ./web
    ports:
      - "3000:3000"
      - "4000:4000"
    init: true
    volumes:
      - dot-wiki:/home/app/.wiki

volumes:
  dot-wiki:
    external:
      name: wiki.localtest.me
  proxy:
    external:
      name: proxy.localtest.me
