version: "2.2"

services:
  proxy:
    image: dobbs/proxy:latest
    init: true
    volumes:
      - "./Caddyfile:/etc/proxy/Caddyfile"
    ports:
      - "80:80"
      - "443:443"
  farm:
    image: dobbs/farm:0.12.2
    init: true
    volumes:
      - dot-wiki:/home/app/.wiki
    environment:
      DOMAIN: localtest.me
      COOKIE: secure
  images:
    image: dobbs/image-transporter
    init: true

volumes:
  dot-wiki:
    external:
      name: wiki.localtest.me
