version: "2.2"

services:
  proxy:
    image: dobbs/proxy:latest
    init: true
    volumes:
      - ./images/image-transporter-Caddyfile:/etc/proxy/image-transporter-Caddyfile
    ports:
      - "80:80"
      - "443:443"
  web:
    image: dobbs/wiki:0.5.0
    build: ./web
    ports:
      - "3000:3000"
      - "4000:4000"
    init: true
    volumes:
      - dot-wiki:/home/app/.wiki
  images:
    build: ./images
    ports:
      - "4010:4010"
    init: true

volumes:
  dot-wiki:
    external:
      name: wiki.localtest.me
