version: "2.2"

services:
  proxy:
    image: dobbs/proxy:0.10.12
    init: true
    environment:
      ORIGIN: farm:3000
    ports:
      - "80:80"
      - "443:443"
  farm:
    extends: farmconfig
    init: true
    depends_on:
      - farmconfig
    command: /home/app/bin/wiki
  farmconfig:
    image: dobbs/farm:0.14.0
    volumes:
      - localtest_me:/home/app/.wiki
    environment:
      DOMAIN: localtest.me
      COOKIE: secure
    command: ./configure-wiki
volumes:
  localtest_me: {}
