version: "2.2"

services:
  proxy:
    image: dobbs/proxy:0.10.10
    init: true
    environment:
      ORIGIN: farm:3000
    ports:
      - "80:80"
      - "443:443"
  farm:
    image: dobbs/farm:0.13.0
    init: true
    volumes:
      - dot-wiki:/home/app/.wiki
    environment:
      DOMAIN: localtest.me
      COOKIE: secure
volumes:
  dot-wiki:
    external:
      name: wiki.localtest.me
