version: "2.2"

services:
  proxy:
    image: dobbs/proxy:0.10.11
    init: true
    environment:
      ORIGIN: farm:3000
    ports:
      - "80:80"
      - "443:443"
  farm:
    extends: farmshare
    init: true
    depends_on:
      - farmconfig
  farmconfig:
    extends: farmshare
    command: ./configure-wiki
  farmshare:
    image: dobbs/farm:0.14.0
    volumes:
      - dot-wiki:/home/app/.wiki
    environment:
      DOMAIN: localtest.me
      COOKIE: secure
volumes:
  dot-wiki:
    external:
      name: wiki.localtest.me
